@startuml Mobile Client - New Sample
autoactivate on

actor User as u
participant App as app << component >>
participant PredictPage as pp << component >>
participant API as api

u -> app : scan QR code with predictionId
app --> pp **
deactivate app
activate pp
pp -> api : getPredictionConfiguration(id: string):
api ->]: REST
return
return IPredictionConfiguration
note left: listen via effect hook

@enduml