@startgantt
Project starts 2021-01-27
saturday are closed
sunday are closed
monday are closed
' and ends 2021-02-19
[Start] happens 2021-01-27
[End] happens 2021-03-30
-- clients --
[c.API] on {Ömer} lasts 2 week and is colored in GreenYellow/Green
[c.App] on {Ömer} lasts 2 days and is colored in GreenYellow/Green
[c.Header] on {Ömer} starts 4 day after [c.App]'s end and lasts 1 day
-- \tdesktop client --
[c.d.LoginPage] on {Ömer} starts at [c.App]'s end and lasts 1 day and is colored in GreenYellow/Green
[c.d.SignupPage] on {Ömer} starts at [c.App]'s end and lasts 1 day and is colored in GreenYellow/Green
[c.d.WorkspacesListPage] on {Ömer} starts at [c.d.SignupPage]'s end and lasts 5 day and is colored in GreenYellow/Green
[c.d.WorkspaceCreationPage] on {Ömer} starts at [c.d.SignupPage]'s end and lasts 5 days and is colored in GreenYellow/Green
[c.d.WorkspacePage] on {Ömer} starts at [c.d.WorkspaceCreationPage]'s end and lasts 5 day and is colored in GreenYellow/Green
[c.d.WorkspaceCollectDataPage] on {Ömer} starts at [c.d.WorkspacePage]'s end and lasts 1 day and is colored in GreenYellow/Green
[c.d.QRView] on {Ömer} starts at [c.d.WorkspaceCollectDataPage]'s end and lasts 2 days and is colored in GreenYellow/Green
[c.d.SampleList] on {Ömer} starts at [c.d.WorkspacePage]'s start and lasts 20 day and is colored in GreenYellow/Green
[c.d.WorkspaceSampleDetailsPage] on {Ömer} starts at [c.d.WorkspacePage]'s start and lasts 2 days and is colored in GreenYellow/Green
[c.d.SampleChart] on {Ömer} starts 2 days after [c.d.WorkspaceSampleDetailsPage]'s end and lasts 5 days and is colored in GreenYellow/Green
[c.d.ModelOptions] on {Ömer} starts 15 days after [c.d.WorkspacePage]'s start and lasts 15 day and is colored in GreenYellow/Green
[c.d.WorkspaceLabels] on {Ömer} starts at [c.d.ModelOptions]'s start and lasts 4 day and is colored in GreenYellow/Green
[c.d.WorkspaceModels] on {Ömer} starts 1 day after [c.d.ModelOptions]'s start and lasts 7 day and is colored in GreenYellow/Green
[c.d.WorkspaceModelDetailsPage] on {Ömer} starts at [c.d.WorkspaceModels]'s end and lasts 4 day and is colored in GreenYellow/Green
[c.d.WorkspaceModelClassifyPage] on {Ömer} starts at [c.d.WorkspaceModels]'s end and lasts 1 day and is colored in GreenYellow/Green
-- \tmobile client --
[c.m.LabelSelectionPage] on {Tarek} {Ömer} starts 35 days after [c.App]'s end and lasts 1 day and is colored in GreenYellow/Green
[c.m.RecordingConfigurationPage] on {Tarek} {Ömer} starts at [c.m.LabelSelectionPage]'s end and lasts 1 day and is colored in GreenYellow/Green
[c.m.RecordingPage] on {Tarek} {Ömer} starts at [c.m.RecordingConfigurationPage]'s end and lasts 8 day and is colored in GreenYellow/Green
[c.m.PredictionPage] on {Tarek} {Ömer} starts at [c.m.RecordingPage]'s end and lasts 4 day and is colored in GreenYellow/Green
-- workspace management --
[w.App] on {Murat} starts 2021-01-29 and  lasts 2 day and is colored in GreenYellow/Green
[w.WorkspaceController] on {Murat} starts 3 days after [w.App]'s end and lasts 5 day and is colored in GreenYellow/Green
[w.WorkspaceModel] on {Murat} starts at [w.WorkspaceController]'s start and lasts 3 day and is colored in GreenYellow/Green
[w.Workspace] on {Murat} starts at [w.WorkspaceModel]'s end and lasts 1 day and is colored in GreenYellow/Green
[w.Sensor] on {Murat} starts at [w.Workspace]'s end and lasts 1 day and is colored in GreenYellow/Green
[w.SampleController] on {Murat} starts at [w.Sensor]'s end and lasts 3 day and is colored in GreenYellow/Green
[w.SampleModel] on {Murat} starts at [w.SampleController]'s start and lasts 3 day and is colored in GreenYellow/Green
[w.Sample] on {Murat} starts at [w.SampleController]'s start and lasts 1 day and is colored in GreenYellow/Green
[w.SensorDataPoints] on {Murat} starts at [w.Sample]'s end and lasts 1 day and is colored in GreenYellow/Green
[w.DataPoint] on {Murat} starts at [w.SensorDataPoints]'s start and lasts 1 day and is colored in GreenYellow/Green
[w.TimeFrame] on {Murat} starts at [w.Sample]'s end and lasts 1 day and is colored in GreenYellow/Green
[w.Label] on {Murat} starts at [w.Sample]'s end and lasts 1 day and is colored in GreenYellow/Green
[w.LabelController] on {Murat} starts at [w.App]'s end and lasts 2 day and is colored in GreenYellow/Green
-- model management --
[m.Main] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.Config] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 1 day and is colored in GreenYellow/Green
[m.asyncDB.MLModelRepository] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 3 day and is colored in GreenYellow/Green 
[m.asyncDB.WorkspaceRepository] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 3 day and is colored in GreenYellow/Green 
[m.syncDB.FileRepository] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 3 day and is colored in GreenYellow/Green 
[m.syncDB.MLModelRepository] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 3 day and is colored in GreenYellow/Green 
[m.syncDB.WorkspaceRepository] on {Enes} {Atalay} starts at [m.Main]'s end and lasts 3 day and is colored in GreenYellow/Green 
[m.CommonRoutes] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.WorkspaceRoutes] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.API] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.Dependancies] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.ExceptionHandling] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.Services] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.ClassifierConfigSpaces] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.classification.Enum] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.classification.Factory] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.feature.Enum] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.imputation.Enum] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.imputation.Factory] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.normalization.Enum] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.ColumnTransformer] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.PipelineFactory] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.Util] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.prediction.DataSetManager] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.PredictionManager] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.Predictor] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.ConfigParsing] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.training.DataSetManager] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.Trainer] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.TrainingManager] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green 
[m.TrainingState] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.DataProcessing] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.SampleParsing] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.DbDoc] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.FeatureExtractionData] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.MLModel] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.PerformanceMetrics] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.PredictionKey] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.Sample] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.Sensor] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.SlidingWindow] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.TrainingConfig] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.TrainingDataSet] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.Workspace] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.MLModel] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.MongoModel] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.Parameters] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.PredictionConfig] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.PredictionData] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.Sensor] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.TrainingConfig] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.TrainingState] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.WorkspaceConfig] on {Tarek} lasts 1 day and is colored in GreenYellow/Green 
[m.DataSource] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.SampleModel] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.WorkspaceDataSource] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[m.DataSource] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
-- authentication --
[a.User] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[a.UserModel] on {Enes} {Atalay} lasts 1 day and is colored in GreenYellow/Green
[a.AuthenticationController] on {Enes} {Atalay} starts at [a.UserModel]'s end and lasts 1 day and is colored in GreenYellow/Green
[a.EmailValidator] on {Enes} {Atalay} starts at [a.AuthenticationController]'s end and lasts 1 day and is colored in GreenYellow/Green
[a.App] on {Enes} {Atalay} starts at [a.AuthenticationController]'s end and lasts 1 day and is colored in GreenYellow/Green
@endgantt